catalogs:
  dev:
    '@arethetypeswrong/core': ^0.18.2
    '@biomejs/biome': ^2.3.7
    '@types/node': ^24.10.1
    '@typescript/native-preview': 7.0.0-dev.20251126.1
    '@virtual-live-lab/eslint-config': ^2.3.1
    '@virtual-live-lab/tsconfig': ^2.1.21
    eslint: ^9.39.1
    eslint-plugin-import-access: ^3.1.0
    pkg-pr-new: ^0.0.60
    publint: ^0.3.15
    release-it: ^19.0.6
    release-it-pnpm: ^4.6.6
    tsdown: ^0.16.7
    typescript: ^5.9.3
    typescript-eslint: ^8.48.0
    unplugin-unused: ^0.5.6
    vite: ^7.2.4
    vitest: ^4.0.14
