allowBuilds:
  esbuild: true

catalogs:
  dev:
    '@arethetypeswrong/core': 0.18.2
    '@types/node': 25.9.1
    '@typescript/native-preview': 7.0.0-dev.20260521.1
    '@virtual-live-lab/tsconfig': 2.1.23
    oxfmt: 0.51.0
    oxlint: 1.66.0
    oxlint-tsgolint: 0.23.0
    pkg-pr-new: 0.0.75
    publint: 0.3.21
    release-it: 20.0.1
    release-it-pnpm: 4.6.6
    tsdown: 0.22.0
    typescript: 6.0.3
    unplugin-unused: 0.5.7
    vitest: 4.1.7

saveExact: true
