catalogs:
  dev:
    '@arethetypeswrong/core': ^0.18.2
    '@types/node': ^25.5.0
    '@typescript/native-preview': 7.0.0-dev.20260323.1
    '@virtual-live-lab/eslint-config': ^2.3.1
    '@virtual-live-lab/tsconfig': ^2.1.21
    eslint: ^9.39.2
    eslint-plugin-import-access: ^3.1.0
    oxfmt: ^0.42.0
    pkg-pr-new: ^0.0.66
    publint: ^0.3.18
    release-it: ^19.2.4
    release-it-pnpm: ^4.6.6
    tsdown: 0.21.4
    typescript: ^5.9.3
    typescript-eslint: ^8.57.2
    unplugin-unused: ^0.5.7
    vitest: ^4.1.1
