catalogs:
  dev:
    '@arethetypeswrong/core': ^0.18.2
    '@types/node': ^25.0.3
    '@typescript/native-preview': 7.0.0-dev.20251217.1
    '@virtual-live-lab/eslint-config': ^2.3.1
    '@virtual-live-lab/tsconfig': ^2.1.21
    eslint: ^9.39.2
    eslint-plugin-import-access: ^3.1.0
    oxfmt: ^0.18.0
    pkg-pr-new: ^0.0.62
    publint: ^0.3.16
    release-it: ^19.1.0
    release-it-pnpm: ^4.6.6
    tsdown: 0.18.0
    typescript: ^5.9.3
    typescript-eslint: ^8.50.0
    unplugin-unused: ^0.5.6
    vite: ^7.3.0
    vitest: ^4.0.16
